## Numpy

### The basics

* NumPy's main object is the homogeneous multidimensional array. Table of elements, all of the same type, indexed by a tuple of positive integers, called the axes, the number of axes is rank.

* Numpy's array class is called `ndarray`. nd.array is not the same as Python standard array.array class, which handles one-dimensional array.

In [3]:
[[1, 0, 0],
 [0, 1, 2]]

[[1, 0, 0], [0, 1, 2]]

* .ndim
    * The number of axes (dimensions) of the array
* .shape
    * The dimensional of the array
* .size
    * Total number of elements of the array
* .dtype 
    * describing the type of element of array. e.g: numpy.int32, numpy.int16, numpy.float64
* .itemsize
    * the size in bytes of each element of arrary
* .data
    * the butter containing the actual elements of the array. Normally index is used to access

#### example

In [4]:
from numpy import *
a = arange(15).reshape(3,5)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))
b = array([6, 7, 8])
print(type(b))

(3, 5)
2
15
int64
8
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Array Creation

1. Using array() function.

In [21]:
import numpy as np
a = array( [2, 3, 4] )
print(a.dtype)
b = array( [2.1, 2.2, 2.3])
print(b.dtype)

int64
float64


In [36]:
print(zeros((3,4))) # create array of all 0
print(ones((2,3,4), dtype = int16)) # create array of all 1
print(empty((3,4))) # create array with random number

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [42]:
# Create sequence of numbers
arange(10, 30, 5)
arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [61]:
linspace(0, 2, 9)
x = linspace(0, 2 * pi, 100)

TypeError: '>' not supported between instances of 'int' and 'str'

### Print Arrays

* Numpy displays array in a similar way of nested lists, but with the following layout
    * The last axis is printed from left to right
    * The second-to-last is printed from top to bottom
    * The rest are printed from top to bottom, with each slice separated from the next by an empty line
    
* One dimensional array printed as rows, two-dimensional as matrix, and three-dimensional as list of matrices

In [1]:
a = arange(6) # 1d array
print(a)
b = arange(12).reshape(4,3) # 2d array
print(b)
c = arange(24).reshape(2,3,4) # 3d array
print(c)

NameError: name 'arange' is not defined

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])